AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Content Moderator - Built from scratch

Globals:
  Function:
    Timeout: 30

Resources:
  ContentModeratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: content_moderator/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - arm64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ContentModeratorFunction.Arn